In [12]:
# 1.Prepare origianl data and synthetic data 

import os
import pandas as pd
import numpy as np


os.chdir('/home/jwkim/ADR/')

data = pd.read_csv("./demo/data/demo_data.csv")
syn_data = pd.read_csv("./demo/data/demo_syn_data.csv")

In [7]:
# 2. Choose the key and target variables

key = ["Gene", "Gender"]
target = "Disease"

In [17]:
# 3. Calculate ADR (Default version)

import ADR

adr = ADR.ADR(data = data, 
              syn_data = syn_data, 
              key = key, 
              target = target)

print("ADR Score: ", np.round(adr.calculate(), 3))

ADR Score:  0.731

In [18]:
adr.orig_cond_dist

   composite_key composite_target  count  cond_prob
0            1_F                N      0   0.000000
1            1_F                Y      2   1.000000
2            1_M                N      1   0.250000
3            1_M                Y      3   0.750000
4            2_F                N      1   0.250000
5            2_F                Y      3   0.750000
6            2_M                N     12   0.857143
7            2_M                Y      2   0.142857
8            3_F                N     12   0.857143
9            3_F                Y      2   0.142857
10           3_M                N      0   0.000000
11           3_M                Y      2   1.000000

In [19]:
adr.syn_cond_dist

   composite_key composite_target  count  cond_prob
0            1_F                N      0   0.000000
1            1_F                Y      0   0.000000
2            1_M                N      0   0.000000
3            1_M                Y      5   1.000000
4            2_F                N      0   0.000000
5            2_F                Y      2   1.000000
6            2_M                N     10   0.833333
7            2_M                Y      2   0.166667
8            3_F                N     16   0.888889
9            3_F                Y      2   0.111111
10           3_M                N      0   0.000000
11           3_M                Y      3   1.000000

In [20]:
# 3. Calculate ADR (Detailed version)

import ADR

adr = ADR.ADR(data = data, 
              syn_data = syn_data, 
              key = key, 
              target = target,
              risk = "accuracy", 
              weight = "gini_impurity",
              imputation = "appr", 
              neighborhood = 2, 
              normalize = True, 
              show_all = True)

score, score_df = adr.calculate()
print("ADR Score: ", np.round(score, 3))
score_df

ADR Score:  0.679

   key     score
0  1_F  0.000000
1  1_M  0.098473
2  2_F  0.098473
3  2_M  0.135967
4  3_F  0.135967
5  3_M  0.210075

In [21]:
adr.orig_cond_dist

   composite_key composite_target  count  cond_prob
0            1_F                N      0   0.000000
1            1_F                Y      2   1.000000
2            1_M                N      1   0.250000
3            1_M                Y      3   0.750000
4            2_F                N      1   0.250000
5            2_F                Y      3   0.750000
6            2_M                N     12   0.857143
7            2_M                Y      2   0.142857
8            3_F                N     12   0.857143
9            3_F                Y      2   0.142857
10           3_M                N      0   0.000000
11           3_M                Y      2   1.000000

In [22]:
adr.syn_cond_dist

   composite_key composite_target  count  cond_prob  imputed_prob
0            1_F                N      0   0.000000      0.650000
1            1_F                Y      0   0.000000      0.350000
2            1_M                N      0   0.000000      0.000000
3            1_M                Y      5   1.000000      1.000000
4            2_F                N      0   0.000000      0.000000
5            2_F                Y      2   1.000000      1.000000
6            2_M                N     10   0.833333      0.833333
7            2_M                Y      2   0.166667      0.166667
8            3_F                N     16   0.888889      0.888889
9            3_F                Y      2   0.111111      0.111111
10           3_M                N      0   0.000000      0.000000
11           3_M                Y      3   1.000000      1.000000